0:
  name: kamehamehon
  head: 27f0e0417bcb011604eca1c197e8b3d8
  say: 希望能够建立一个Geek自己的乐园
  blog: primesplus.com/blog
  twitter: mikecai
  gurudigger: 13626
1:
  name: 404
  head: 00fa008b6008f3b8bdf6c870f43accb1
  say: 爱在此，乐在此，分享彼此！期待我们的 0x65 Geek Bar 早点跟大家见面！:)
  sina: awhy
  twitter: l404
  gurudigger: 12214
  github: why404
2:
  name: Ray58750034
  head: c8e6a7893b84dca0201cfa12624a22f0
  say: 0x65的wifi应该是免费和翻墙的
3:
  name: Frank_Xu
  head: /images/Frank_Xu.jpg
  say: 你有一个苹果，我有一个苹果，彼此交换，我们每人仍只有一个苹果。你有一种思想，我有一种思想，彼此交换，我们每人就有了两种思想。Ox65,一个交流思想，迸发创意的地方。
  twitter: franky_xhl
4:
  name: linjunhalida
  head: 946dbc66d19ba815ffec20d05f138f73
  say: 希望能够让geek们出来认识和交流, 一起讨论如何改变世界!
  blog: blog.linjunhalida.com
  twitter: linjunhalida
  github: halida
  gurudigger: 5140
5:
  name: c2h2
  head: 4c3a420fa1c7153dc5331020dcad6b64
  say: 加油 快办出来.
  twitter: c2h2
  github: c2h2
6:
  name: Logan
  head: 2c287c5c7e3ad9ed856658abc11c9ec8
  say: 一直很期待这种归属感。
  twitter: xorcerer
  github: xorcerer
7:
  name: Miclle
  head: 004794ff3508e44c4902fd82ef4027f4
  say: 没事就来聊聊生活，扯扯工作
  blog: miclle.me
  twitter: miclle
  github: miclle
8:
  name: apoclast
  head: 94e2904aff07266d1be6b2e0e647bc47
  say: Make a group of geeks that is not virtual.
  blog: apoclast.com
  twitter: apoclast
  github: apoclast
9:
  name: 小田
  head: 495e22cb07fe2dcf0090beefdc8f74bd
  say: 我要喝铁观音
  gurudigger: 13654
10:
  name: Hui Wang
  head: 984c6760e980d1e9060df87bcee51d8e
  say: 希望有一天, 0x65 成为中国的 YCombinator, 甚至更好
11:
  name: Stephen
  head: f21e603b2b1d2fdb85a722b711997a09
  say: 期待0x65早点开张。 
  blog: stephen.cnblogs.com
  twitter: onetownx
  github: onetown
14:
  name: kenshin
  head: 05dcd7af065d8e5961d3823a72d12165
  say: 称霸上海 称霸全国 称霸全球
  blog: kenbeit.com
  twitter: kenshin54
  gurudigger: 30594
  github: kenshin54
15:
  name: yuanyi
  head: 1ead00628148e2cc3eacbf671824c62d
  say: 希望能够成为Geek聚集地
  twitter: yuanyiz
  github: yzhang
16:
  name: Vincent 4J
  head: 307ba67a1d4f19ef2188cd76f40f4e48
  say: 预折腾，请到0x65来。
  blog: vc4j.com
  twitter: vincent4j
  sina: vincent4j
18:
  name: silenceroom
  head: 5a890a158f6cb5c2a697684fe6f44c7b
  say: 想找个地方跟有相同兴趣的人喝喝咖啡，扯扯淡。
  blog: teccolin.info/wordpress
  twitter: silenceroom
  gurudigger: 33974
19:
  name: ZoOL
  head: 1650a843ba1c7eaf4809260c5c51922e
  say: 一直很期待这么一个Geek 基地  认识更多的朋友
  blog: ZoOL.me
  gurudigger: 7062
  github: foxzool
20:
  name: Sumhat
  head: 6820f90f9b9eb2914107203980b52366
  say: 期待0x65孵化出的多姿多彩的创意……
  blog: leonax.net
  twitter: FinalLaugh
21:
  name: walle
  head: 79a37bbfe2da37eec340f9eaa219c935
  say: 不求它有多奢华，但求它是geek心中的栖息地
  blog: bengshuo.com
  twitter: uulele
  gurudigger: 27236
  github: uulele
22:
  name: chenyuejie
  head: 2789b55508c5ed4366b1f57ccf419b0c
  say: 喝进去的是咖啡, 挤出来的是10
  twitter: c9
23:
  name: quake
  head: 748dfca10db6ade9156d9377fc05def7
  say: by geeks, for geeks
  blog: quake.iteye.com
  twitter: quakewang
  gurudigger: 6114
  github: quake
24:
  name: Automan
  head: 43c3b1ab6efc822530be95feff5089b7
  say: 要有热巧克力
  blog: btli1001.com
25:
  name: Ben
  head: 34968eb49b6dfd928781f7cd180e2a00
  say: 更多Geek，更多创意，更美好的未来，哈哈~
  blog: zfben.com
  twitter: zfben
  gurudigger: 18805
  github: benz303
26:
  name: Nathan Bao
  head: 6a2281c43ec828dc12592578860acc34
  say: 如果真能建成，真的很COOL啊！很期待，哈哈~
  blog: renren.com/profile.do?id=243802945&v=blog
27:
  name: Meaglith Ma
  head: 3990405c0bc2257d4402c95460861e03
  say: 不只开在上海，一定要到北京来。
  blog: start-up.im
  twitter: genedna
  github: genedna
28:
  name: GlennZhang
  head: 9756b9f6d87fe6c6aad16fad05bc9502
  say: 希望0x65能成为Geeker的文化基地，推动Hacker文化、开源文化、Geeker文化的发展，继承和发展自由、平等、随意、突破、共享的精神，让更多新人了解并加入这个大家庭共同创造奇迹。
  blog: hi.baidu.com/sunblackshine
  gurudigger: 35599
  github: zy-sunshine
29:
  name: Steven Cheng
  head: de9c0a855a846752b66f705ad0a3edfd
  say: 0x65是Geek们共同维护的精神家园，想信这里将会创造奇迹。
30:
  name: Mike Chen
  head: 8c1efc4f4618aa68b18c88f2bcaa5564
  say: 心中憧憬的那份创业火焰，希望认识更多的朋友齐拾材，共添薪
  blog: gchen.cn
  twitter: chagel
  github: chagel
31:
  name: u20024804
  head: 6a8f8285a42a76f5e47159c9f09a7c4f
  say: 真的一直很期待这么一个Geek基地
  twitter: u20024804
  gurudigger: 36334
32:
  name: Mike Liang
  head: db169bfaf47d339de43a6d9abd057860
  say: 赞一个! :-)
  blog: www.liangwenke.com
  twitter: liangwenke
  gurudigger: 36312
  github: liangwenke
